set(MARK_SHOT_CLI_SOURCES
    src/cli/doctor_cli.cpp
    src/cli/doctor_cli.h
    src/cli/headless_capture.cpp
    src/cli/headless_capture.h
    src/cli/headless_capture_options.cpp
    src/cli/headless_capture_options.h
    src/cli/recording_cli.cpp
    src/cli/recording_cli.h
    src/cli/window_capture_cli.cpp
    src/cli/window_capture_cli.h
)
